---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgg-app-cm
  labels: 
    name: bgg-app-cm
data:
  BGG_DB_HOST: bgg-db-svc
  BGG_DB_USER: root
---
apiVersion: v1
kind: Secret
metadata:
  name: bgg-app-secret
  labels: 
    name: bgg-app-secret
type: Opaque
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgg-app-v1-deploy
  labels:
    name: bgg-app-v1-deploy
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      name: bgg-app-v1-deploy
  template:
    metadata:
      name: bgg-app-v1-deploy
      labels:
        name: bgg-app-v1-deploy
        dept: eng
    spec:
      containers:
      - name : bgg-app-v1
        image: stackupiss/bgg-backend:v1
        args: ["--prefix","/v1"]
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: bgg-app-cm
        - secretRef:
            name: bgg-app-secret
---
apiVersion: v1
kind: Service
metadata:
  name: bggappv1-svc
  labels:
    name: bggappv1-svc
spec:
  type: ClusterIP
  selector:
    name: bgg-app-v1-deploy
  ports:
  - port: 8080
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bgg-ing
  labels:
    name: bgg-ing
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: “5“
spec:
  ingressClassName: nginx
  rules:
  - host: bgg.146.190.5.180.nip.io
    http:
      paths:
      - path: /v1
        pathType: Prefix
        backend: 
          service:
            name: bggappv1-svc
            port:
              number: 8080
      - path: /v2
        pathType: Prefix
        backend: 
          service:
            name: bggappv2-svc
            port:
              number: 8080