---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgg-db
  labels:
    name: bgg-db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bgg-db
  template:
    metadata:
      name: bgg-db
      labels:
        name: bgg-db
        dept: eng
    spec:
      containers:
      - name : bgg-db
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: bgg-db-port
          containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  labels:
    name: bggdb-svc
spec:
  type: ClusterIP
  selector:
    name: bgg-db
  ports:
  - port: 3306
    targetPort: bgg-db-port