---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bggapp-cm
  labels: 
    name: bggapp-cm
data:
  BGG_DB_HOST: bggdb-svc
  BGG_DB_USER: root
---
apiVersion: v1
kind: Secret
metadata:
  name: bggapp-secret
  labels: 
    name: bggapp-secret
type: Opaque
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  labels:
    name: bggapp-deploy
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      name: bggapp-deploy
  template:
    metadata:
      name: bggapp-deploy
      labels:
        name: bggapp-deploy
        dept: eng
    spec:
      containers:
      - name : bggapp-deploy-container
        image: stackupiss/bgg-backend:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: bggapp-cm
        - secretRef:
            name: bggapp-secret
        livenessProbe:
          httpGet: 
            path: /healthz
            port: 3000
            scheme: HTTP
---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  labels:
    name: bggapp-svc
spec:
  type: LoadBalancer
  selector:
    name: bggapp-deploy
  ports:
  - port: 80
    targetPort: 3000